/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.93
 * Generated at: 2025-12-12 05:40:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.student;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.LibraryStudentDAO;
import dao.LibraryStudentJDBCDAO;
import beans.BookIssued;
import beans.Book;
import java.util.List;
import dao.LibraryDAO;
import dao.LibraryJDBCDAO;

public final class findReservedBooks_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("dao.LibraryStudentJDBCDAO");
    _jspx_imports_classes.add("beans.Book");
    _jspx_imports_classes.add("beans.BookIssued");
    _jspx_imports_classes.add("dao.LibraryDAO");
    _jspx_imports_classes.add("dao.LibraryStudentDAO");
    _jspx_imports_classes.add("dao.LibraryJDBCDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Reserved Books</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("<link href=\"../bootstrap-4.0.0/bootstrap-4.0.0/dist/css/bootstrap.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-light\">\r\n");
      out.write("\r\n");
      out.write("<!-- NAVBAR -->\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("  <a class=\"navbar-brand\" href=\"#\">Library Admin</a>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"ml-auto text-white\">\r\n");
      out.write("    Welcome ");
      out.print(session.getAttribute("name"));
      out.write("  \r\n");
      out.write("    <a href=\"../Logout.jsp\" class=\"btn btn-sm btn-danger ml-2\">Logout</a>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container mt-4\">\r\n");
      out.write("<!-- Page Content -->\r\n");
      out.write("<div class=\"container mt-4\">\r\n");
      out.write("    <div class=\"card shadow-sm\">\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"mb-3\">Student Dashboard</h4>\r\n");
      out.write("\r\n");
      out.write("            <!-- Horizontal Menu -->\r\n");
      out.write("            <ul class=\"nav nav-pills justify-content-center\">\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"./findAllBooks.jsp\">ð All Books</a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"./findReservedBooks.jsp\">ð Reserved Books</a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"./findIssuedBooks.jsp\">ð Issued Books</a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"./findRenewaledBooks.jsp\">ð Renewaled Books</a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"./findReturnedBooks.jsp\">â Returned Books</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");

    try {
        LibraryStudentDAO dao = LibraryStudentJDBCDAO.getInstance();
        int regId=((Integer)session.getAttribute("regId")).intValue();
        List<BookIssued> booksIssued = dao.findReservedBooks(regId);

      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card shadow\">\r\n");
      out.write("        <div class=\"card-header bg-primary text-white\">\r\n");
      out.write("            <h4 class=\"mb-0\">Reserved Books</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card-body p-0\">\r\n");
      out.write("            <table class=\"table table-striped table-hover mb-0\">\r\n");
      out.write("                <thead class=\"thead-dark\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>IssuedId</th>\r\n");
      out.write("                        <th>ISBN</th>\r\n");
      out.write("                        <th>Book Name</th>\r\n");
      out.write("                        <th>RegId</th>\r\n");
      out.write("                        <th>Name</th>\r\n");
      out.write("                        <th>Reserve Date</th>\r\n");
      out.write("                        <th>Status</th>\r\n");
      out.write("                        <th>Action</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("\r\n");
      out.write("                <tbody>\r\n");
      out.write("                ");

                    for(BookIssued bookIssued : booksIssued) {
                
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>");
      out.print(bookIssued.getIssueId());
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print(bookIssued.getIsbn());
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print(bookIssued.getBookName());
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print(bookIssued.getRegId());
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print(bookIssued.getName());
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print(bookIssued.getReserveDate());
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print(bookIssued.getStatus());
      out.write("</td>\r\n");
      out.write("                        <td>-</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                ");

                    }
                
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");

    } catch(Exception e) {
        e.printStackTrace();
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
